BEGIN TRANSACTION;

UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = NULL, codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'BIODERMA', contenido_neto_Des = '40ML', blister_Des = 0, cantidad_presentacion_Des = NULL, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '3401353789500';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'Metamizol', concentracion_Des = '1GR/2ML', forma_farmaceutica_Des = 'Solución Inyectable', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '2ML', blister_Des = 0, cantidad_presentacion_Des = 1, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '5803';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'GRAGEAS', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'CENTRUM', contenido_neto_Des = NULL, blister_Des = 0, cantidad_presentacion_Des = 30, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6811291256816';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'Complejo B', concentracion_Des = NULL, forma_farmaceutica_Des = 'AMP I.V./I.M', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'ZAKIMED', contenido_neto_Des = NULL, blister_Des = 0, cantidad_presentacion_Des = 3, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6921875009179';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'Ceftriaxona', concentracion_Des = '1g', forma_farmaceutica_Des = 'inyectable', codigo_atc_Des = NULL, requiere_recipe_Des = 1, generico_Des = 1, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Ceftriaxona', contenido_neto_Des = NULL, blister_Des = 0, cantidad_presentacion_Des = NULL, url_imagen = 'https://image.tuasaude.com/media/article/oo/xe/ceftriaxona-rocefin_27270.jpg', origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6936292193912';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'SULFATO FERROSO; ACIDO FOLICO', concentracion_Des = '200MG/0.25MG', forma_farmaceutica_Des = NULL, codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = NULL, blister_Des = 0, cantidad_presentacion_Des = NULL, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = 'None';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'VITAMINA C', concentracion_Des = NULL, forma_farmaceutica_Des = 'solucion', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'pediatrico', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '120ML', blister_Des = 0, cantidad_presentacion_Des = NULL, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6977234270391';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'BACITRACINA', concentracion_Des = NULL, forma_farmaceutica_Des = 'UNGÜENTO', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '15GR', blister_Des = 0, cantidad_presentacion_Des = NULL, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6977234270469';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'FLUCONAZOL', concentracion_Des = '150MG', forma_farmaceutica_Des = 'TABLETA', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = 'Colmed', marca_Des = 'COFLUX', contenido_neto_Des = NULL, blister_Des = 0, cantidad_presentacion_Des = 2, url_imagen = 'https://lh3.googleusercontent.com/_x3734qPT4uKiev4ykMOrA7lMNutzedSsLYA4UrgIW9qBgOjMnk-UFZcCf46R_04pBzE8x67FM-kUM1cCsWr-NAGHXrmFCdIoM7h4vsgogB0g6mp', origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6977234270629';
UPDATE Procurement.por_aprobacion_equivalencias SET es_medicamento = 1, clasificacion_insumo_Des = NULL, principio_activo_Des = 'CETIRIZINA', concentracion_Des = '5MG/5ML', forma_farmaceutica_Des = 'JARABE', codigo_atc_Des = NULL, requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = NULL, origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'CIZTAMIN', contenido_neto_Des = '60ML', blister_Des = 0, cantidad_presentacion_Des = 60, url_imagen = NULL, origen_dato = 'IA_INVESTIGATED_V10' WHERE codigo = '6977234270780';

COMMIT;
