BEGIN TRANSACTION;

UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Heparina sódica', concentracion_Des = '250 UI/g', forma_farmaceutica_Des = 'Gel', codigo_atc_Des = 'C05B', codigo_atc_profundo_Des = 'C05BA03', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '30', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000014';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Testosterona', concentracion_Des = '250 mg/ml', forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = 'A14A', codigo_atc_profundo_Des = 'A14AA01', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Testo-Mix', contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000018';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Diosmina; Hesperidina', concentracion_Des = '450 mg; 50 mg', forma_farmaceutica_Des = 'Tableta', codigo_atc_Des = 'C05C', codigo_atc_profundo_Des = 'C05CA53', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'Drotafarma', marca_Des = NULL, contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000001';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Sistema de drenaje', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'Brixmedic', marca_Des = 'Portovac', contenido_neto_Des = '1', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000008';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Gabapentina; Cianocobalamina', concentracion_Des = '75 mg; 750 mcg', forma_farmaceutica_Des = 'Cápsula', codigo_atc_Des = 'N03A', codigo_atc_profundo_Des = 'N03AX12', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Gababrix-B', contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000005';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Itraconazol; Secnidazol', concentracion_Des = NULL, forma_farmaceutica_Des = 'Cápsula', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'ITRASEC', contenido_neto_Des = '1', cantidad_presentacion_Des = 12, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000003';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Apósito', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Euroderm Plus', contenido_neto_Des = '1', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000011';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Ondansetrón', concentracion_Des = '4 mg/2 ml', forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = 'A04A', codigo_atc_profundo_Des = 'A04AA01', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000012';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Sitagliptina; Metformina', concentracion_Des = '50 mg; 500 mg', forma_farmaceutica_Des = 'Tableta', codigo_atc_Des = 'A10B', codigo_atc_profundo_Des = 'A10BD07', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Siglipmet', contenido_neto_Des = '1', cantidad_presentacion_Des = 30, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000004';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Ketoprofeno', concentracion_Des = '100 mg/2 ml', forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = 'M01A', codigo_atc_profundo_Des = 'M01AE03', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = NULL, cantidad_presentacion_Des = NULL, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000017';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Amoxicilina; Ácido Clavulánico', concentracion_Des = '875 mg/125 mg', forma_farmaceutica_Des = 'Tableta', codigo_atc_Des = 'J01C', codigo_atc_profundo_Des = 'J01CR02', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000000';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Solución tópica', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Isospray Plus', contenido_neto_Des = '120', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000002';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Media de compresión', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '1', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000006';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Tensiómetro digital', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = 'Skymedical', contenido_neto_Des = '1', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000007';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Tubo de drenaje', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'Brixmedic', marca_Des = 'Brixmedic', contenido_neto_Des = '1', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000009';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = NULL, codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'BRIX MEDIC', marca_Des = 'Portovac', contenido_neto_Des = '400', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000010';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Metotrexato', concentracion_Des = '50 mg/2 ml', forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = 'L01B', codigo_atc_profundo_Des = 'L01BA01', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 1, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '2', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000013';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Comprimido', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'SNC PHARMA', marca_Des = 'KOLNASI', contenido_neto_Des = '1', cantidad_presentacion_Des = 30, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000015';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '1', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000016';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = NULL, concentracion_Des = NULL, forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = NULL, codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = NULL, marca_Des = NULL, contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '900000000019';

COMMIT;
