BEGIN TRANSACTION;

UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Buprenorfina', concentracion_Des = '35 mcg/h', forma_farmaceutica_Des = 'Parche transdérmico', codigo_atc_Des = 'N02A', codigo_atc_profundo_Des = 'N02AE01', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 1, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'Grünenthal', marca_Des = 'Transtec', contenido_neto_Des = '1', cantidad_presentacion_Des = 5, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '759100000001';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Diazepam', concentracion_Des = '10 mg/2 ml', forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = 'N05B', codigo_atc_profundo_Des = 'N05BA01', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 1, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'Laboratorios Roche', marca_Des = 'Valium', contenido_neto_Des = '1', cantidad_presentacion_Des = 10, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '759100000005';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Amoxicilina; Ácido clavulánico', concentracion_Des = '250 mg/5 ml; 62.5 mg/5 ml', forma_farmaceutica_Des = 'Polvo para suspensión oral', codigo_atc_Des = 'J01C', codigo_atc_profundo_Des = 'J01CR02', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'PEDIATRICO', origen_Des = NULL, fabricante_Des = 'GSK', marca_Des = 'Augmentin', contenido_neto_Des = '120', cantidad_presentacion_Des = 1, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '759100000002';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Insulina Glargina', concentracion_Des = '100 UI/ml', forma_farmaceutica_Des = 'Solución inyectable', codigo_atc_Des = 'A10A', codigo_atc_profundo_Des = 'A10AE04', modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'NO_DEFINIDO', origen_Des = NULL, fabricante_Des = 'Sanofi Aventis', marca_Des = 'Lantus SoloStar', contenido_neto_Des = '1', cantidad_presentacion_Des = 5, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '759100000003';
UPDATE Procurement.por_aprobacion_equivalencias SET principio_activo_Des = 'Paracetamol, Fenilefrina, Clorfeniramina', concentracion_Des = '650 mg; 10 mg; 4 mg', forma_farmaceutica_Des = 'Polvo granulado para solución oral', codigo_atc_Des = 'R05X', codigo_atc_profundo_Des = NULL, modelo_ia_Des = 'deepseek_v4_flash', requiere_recipe_Des = 0, generico_Des = 0, segmento_etario_Des = 'ADULTO', origen_Des = NULL, fabricante_Des = 'Novartis', marca_Des = 'Teraflu Forte', contenido_neto_Des = '1', cantidad_presentacion_Des = 6, origen_dato = 'IA_INVESTIGATED_V11_ORCHESTRATOR' WHERE codbarras = '759100000004';

COMMIT;
